//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Categoria
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Categoria()
        {
            this.InventarioArticulos = new HashSet<InventarioArticulo>();
        }
    
        public int Id { get; set; }
        public string Codigo { get; set; }

        [Required(ErrorMessage = "El Campo {0} Es Requerido")]
        public string Descripcion { get; set; }

        [Display(Name = "Activo")]
        public Nullable<bool> Estatus { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InventarioArticulo> InventarioArticulos { get; set; }
    }
}
