//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ClientesMetodosPago
    {
        public int ID_Tipo_Pago { get; set; }
        public Nullable<int> ID_Cliente { get; set; }
        public string Pago_Cuenta { get; set; }
        public string Pago_Tipo_Cuenta { get; set; }
        public string Fecha_Expiracion { get; set; }
        public Nullable<int> CCV { get; set; }
        public string Institucion_Bancaria { get; set; }
    }
}
