//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleVenta
    {
        public int Id { get; set; }
        public int Id_Venta { get; set; }
        public int Id_Articulo { get; set; }
        public int Id_MovInventario { get; set; }
        public int Cantidad { get; set; }
        public decimal PrecioUnitarioVenta { get; set; }
        public decimal PrecioVenta { get; set; }
        public decimal DescuentoVenta { get; set; }
        public Nullable<bool> Estatus { get; set; }
    
        public virtual InventarioArticulo InventarioArticulo { get; set; }
        public virtual Venta Venta { get; set; }
    }
}
