//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleMovInventario
    {
        public int Id { get; set; }
        public int Id_Ingreso { get; set; }
        public int Id_Articulo { get; set; }
        public decimal Precio_Compra { get; set; }
        public decimal Precio_Venta { get; set; }
        public int Stock_Inicial { get; set; }
        public int Stock_Actual { get; set; }
        public System.DateTime Fecha_produccion { get; set; }
        public System.DateTime Fecha_vencimiento { get; set; }
        public Nullable<bool> Estatus { get; set; }
        public Nullable<int> Id_Ventas { get; set; }
        public string Requisicion { get; set; }
    
        public virtual Venta Venta { get; set; }
        public virtual InventarioArticulo InventarioArticulo { get; set; }
    }
}
