//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmpresaConfig
    {
        public int EmpresaID { get; set; }
        public string NombreEmpresa { get; set; }
        public string RNC { get; set; }
        public int NCF01_Proximo { get; set; }
        public int NCF02_Proximo { get; set; }
        public int NCF03_Proximo { get; set; }
        public int NCF04_Proximo { get; set; }
        public int NCF14_Proximo { get; set; }
        public int NCF15_Proximo { get; set; }
        public double TasaItbisActual { get; set; }
        public string ArchivoLogo { get; set; }
        public string ArchivoTipografia { get; set; }
    }
}
