//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Login
    {
        public int LoginID { get; set; }

        [Display(Name = "Usuario")]
        public string UserName { get; set; }

        [Required(ErrorMessage = "El Campo {0} Es Requerido")]
        [Display(Name = "Contraseña")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name = "Nombre")]
        public string PersonalName { get; set; }

        [EmailAddress(ErrorMessage = "Favor introducir un correo valido")]
        public string Email { get; set; }

        [Display(Name = "Role ID")]
        public Nullable<int> LoginRoleID { get; set; }

        [Display(Name = "Activo")]
        public Nullable<bool> LoginEstatus { get; set; }

        [Required(ErrorMessage = "El Campo {0} Es Requerido")]
        [Compare("Password", ErrorMessage = "Las Contraseñas No Coinciden")]
        [Display(Name = "Confirmar Contraseña")]
        [DataType(DataType.Password)]
        public string ConfirmPassword { get; set; }

        public virtual Role Role { get; set; }
    }
}
