//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RepuestoEntities : DbContext
    {
        public RepuestoEntities()
            : base("name=RepuestoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<CarroCompra> CarroCompras { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<ClientesMetodosPago> ClientesMetodosPagoes { get; set; }
        public virtual DbSet<DetalleMovInventario> DetalleMovInventarios { get; set; }
        public virtual DbSet<DetalleVenta> DetalleVentas { get; set; }
        public virtual DbSet<Empleado> Empleados { get; set; }
        public virtual DbSet<EmpresaConfig> EmpresaConfigs { get; set; }
        public virtual DbSet<InventarioArticulo> InventarioArticulos { get; set; }
        public virtual DbSet<Presentacion> Presentacions { get; set; }
        public virtual DbSet<Proveedore> Proveedores { get; set; }
        public virtual DbSet<Venta> Ventas { get; set; }
        public virtual DbSet<Login> Logins { get; set; }
        public virtual DbSet<MainMenu> MainMenus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<SubMenu> SubMenus { get; set; }
        public virtual DbSet<Categoria> Categorias { get; set; }
    
        public virtual ObjectResult<ListaMenuActivo_Result> ListaMenuActivo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaMenuActivo_Result>("ListaMenuActivo");
        }
    
        public virtual ObjectResult<ListaMenuDesactivado_Result> ListaMenuDesactivado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaMenuDesactivado_Result>("ListaMenuDesactivado");
        }
    
        public virtual ObjectResult<ListaMenuTodos_Result> ListaMenuTodos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ListaMenuTodos_Result>("ListaMenuTodos");
        }
    }
}
