//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SistemaRepuesto.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SubMenu
    {
        public int SubID { get; set; }
        public string SubDescripcion { get; set; }
        public string SubController { get; set; }
        public string SubAction { get; set; }
        public Nullable<int> SubMenuID { get; set; }
        public Nullable<int> SubRoleID { get; set; }
    
        public virtual MainMenu MainMenu { get; set; }
        public virtual Role Role { get; set; }
    }
}
